"""channel messages cascade delete

Revision ID: dc1259e0e7eb
Revises: 5b45c9a38825
Create Date: 2024-11-19 17:48:33.933089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1259e0e7eb'
down_revision: Union[str, None] = '5b45c9a38825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_channel_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_channel_id_fkey', 'message', 'channel', ['channel_id'], ['id'])
    # ### end Alembic commands ###
